### PR TITLE
Add command that lists unique union of installed themes

### PR DESCRIPTION
**Pull request by chrokh**
A quick solution for listing unique union of installed themes.

Not well versed in bash :) so feel free to refactor or ask me to refactor as you see fit.

### CODE REVIEW

**Comment by AuditeMarlow** [comment]
This looks pretty clean imo, the problem is, however, that it can take a long time to "load" the results. I'm thinking maybe we should run this when a user installs a new template, store the results in a (cached) file somewhere, and just `cat` the file on calling `base16-manager list-themes`. That way we don't have to scan all the directories before dumping a result.

**Comment by chrokh** [comment]
Makes sense. Please see updated PR.

`recache_themes()` now stores the list of themes in "${CONFIG_PATH}/themes"`, and is rerun on every `update()`, `install()`, and `uninstall()`.

Minor: Not sure whether `"${CONFIG_PATH}/themes"` should be stored in a variable at the top of the script or be "duplicated" over `recache_themes()` and list_themes()` as it is now. Opinions welcome.

**Comment by AuditeMarlow** [comment]
I've finally found some time to look more closely at this. You're running a subshell using `find` to get the basename of the file, but this is... Kind of redundant as `find` itself has a formatting option as followed:

```sh
find ${CONFIG_PATH}/ -name 'base16-*' -printf "%f\n"
```

So I'd say, instead of running the `-exec` flag, we just format the output, and pipe that to the 2 `sed` commands like this:

```sh
find ${CONFIG_PATH}/ -name 'base16-*' -printf "%f\n" | sed "s/\..*//" | sed "s/base16-//" | sort | uniq
```

This is lightning fast compared to your method, and saves us the trouble from caching the themes at all. :)

**Comment by AuditeMarlow** [comment]
I've upgraded this PR's funcionality using previously mentioned method, found in 037eefe. Thanks a lot, though! It's people like you that keep me inspired to keep me going. :)

**Comment by chrokh** [comment]
Yikes. Had no idea subshells were that costly. Thanks!

**Pull request merged**
