### PR TITLE
Adds support for aaron-williamson/base16-alacritty

### PR DESCRIPTION
**Pull request by naps62**
Support for https://github.com/aaron-williamson/base16-alacritty

This works by `awk`'ing an existing alacritty config file. Since it's a YAML format, with only 1 level of nesting on the colors section (fortunately), it's somewhat trivial to delete the relevant section and append a new one with the desired colors

### CODE REVIEW

**Comment by naps62** [comment]
@AuditeMarlow can you take a look at this? :)

(cleaning up old PRs. My OCD is hitting me today :smile: )

**Comment by theova** [comment]
I'm sorry for the late reply - thanks for keeping up! Cool that you found the way to base16-manager and made your PR :+1: 

Please make sure, that your commit passes [all checks](https://travis-ci.org/AuditeMarlow/base16-manager). We will look at your code after passing all tests.

Furthermore consider please the [Contributing guidelines](https://github.com/AuditeMarlow/base16-manager/blob/master/CONTRIBUTING.md).

**Comment by naps62** [comment]
@theova thanks for the reply. You're right, I completely missed the build failure. My bad there :)

Already fixed, and I'll update the PR description to be a bit more complete

**Comment by theova** [comment]
After a fresh installation of alacritty, I get the following errors:
```
 ./base16-manager set gruvbox-dark-hard
awk: cmd. line:1: delete==1 && /^[^ ].+/ {delete=0} $1 == "colors:" {delete=1; next} delete != 1
awk: cmd. line:1: ^ syntax error
awk: cmd. line:1: delete==1 && /^[^ ].+/ {delete=0} $1 == "colors:" {delete=1; next} delete != 1
awk: cmd. line:1:                               ^ syntax error
awk: cmd. line:1: delete==1 && /^[^ ].+/ {delete=0} $1 == "colors:" {delete=1; next} delete != 1
awk: cmd. line:1:                                                          ^ syntax error
awk: cmd. line:1: delete==1 && /^[^ ].+/ {delete=0} $1 == "colors:" {delete=1; next} delete != 1
awk: cmd. line:1:                                                                    ^ syntax error
```

Probably, you did miss to check, wether there is already an existing config file?

`set_xresources()` may serve as an example for a good edge case handling.

Please don't forget to comment your code when necessary (e.g. what does the awk command?).

**Comment by theova** [comment]
I've just seen: Probably, you can set alacritty with the funciton `set_generic` by setting the parameters accordingly?

**Comment by theova** [comment]
I'm closing this issue due to inactivity.

Feel free to reopen it for applying changes, further discussions, and asking for help. Still, it would be cool, to see alacritty supported by base16-manager.

**Pull request closed without merging**
